import type { MetadataRoute } from "next";

const SITE = "https://financial-terminal-peach.vercel.app";

/** /robots.txt, generated by the App Router.
 *
 *  Only the public marketing surface is crawlable. Everything behind the login
 *  wall renders nothing useful to a bot anyway (it is a client-rendered
 *  authenticated terminal), and /admin must never be indexed, so it is
 *  disallowed explicitly rather than relying on the auth redirect. */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: { userAgent: "*", allow: "/", disallow: ["/admin", "/account"] },
    sitemap: `${SITE}/sitemap.xml`,
  };
}
