import type { MetadataRoute } from "next";

const SITE = "https://financial-terminal-peach.vercel.app";

/** /robots.txt, generated by the App Router.
 *
 *  This used to say "only the public marketing surface is crawlable" while no
 *  marketing surface existed, and allowed "/" — so the only thing a crawler
 *  could index was the authenticated app's chrome.
 *
 *  The app routes are now disallowed explicitly rather than left to the auth
 *  redirect, because the redirect is CLIENT-SIDE: the prerendered HTML is real
 *  and indexable, it just contains nav labels instead of content. Relying on a
 *  redirect a crawler never executes is how a dashboard shell ends up in
 *  search results.
 *
 *  Revisit per route if any of them ever renders content server-side. */
export default function robots(): MetadataRoute.Robots {
  return {
    // Crawling is ALLOWED everywhere, and that is deliberate — it is not an
    // oversight and it is not a weaker version of the previous attempt.
    //
    // The first attempt at this listed the app routes under `disallow`. Two
    // things were wrong with it. It did not even work: robots.txt is
    // allow-by-default, so `allow:` lines exclude nothing and "/" stayed
    // crawlable with no `Disallow: /` anywhere — verified in the built
    // robots.txt. And the instrument was wrong anyway: Disallow blocks
    // CRAWLING, while what we want is to stop INDEXING. A URL that is
    // disallowed can never be re-fetched, so a crawler never sees the noindex
    // and anything already in the index stays there as a title-only result.
    //
    // So indexing is now controlled by a per-page `robots: { index: false }`,
    // defaulted at the root layout and opted back in by the public pages, and
    // this file's job is simply to let crawlers reach those pages to read it.
    rules: { userAgent: "*", allow: "/" },
    sitemap: `${SITE}/sitemap.xml`,
  };
}
