import type { MetadataRoute } from "next";

const SITE = "https://financial-terminal-peach.vercel.app";

/** /robots.txt, generated by the App Router.
 *
 *  This used to say "only the public marketing surface is crawlable" while no
 *  marketing surface existed, and allowed "/" — so the only thing a crawler
 *  could index was the authenticated app's chrome.
 *
 *  The app routes are now disallowed explicitly rather than left to the auth
 *  redirect, because the redirect is CLIENT-SIDE: the prerendered HTML is real
 *  and indexable, it just contains nav labels instead of content. Relying on a
 *  redirect a crawler never executes is how a dashboard shell ends up in
 *  search results.
 *
 *  Revisit per route if any of them ever renders content server-side. */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: ["/login", "/privacy", "/terms", "/disclosures"],
      disallow: [
        "/admin", "/account", "/set-password",
        // Auth-gated app routes: real HTML, no content.
        "/terminal", "/screeners", "/portfolio", "/alerts", "/news",
        "/macro", "/global", "/quant", "/sharks", "/workspace", "/tearsheet",
      ],
    },
    sitemap: `${SITE}/sitemap.xml`,
  };
}
