import type { MetadataRoute } from "next";

const SITE = "https://financial-terminal-peach.vercel.app";

// The publicly meaningful routes. Per-account surfaces (/account, /admin) and
// deep-link-only pages (/tearsheet, which needs a ticker query) are left out —
// a sitemap is a list of pages worth indexing, not every route that resolves.
const ROUTES = [
  "", "/terminal", "/screeners", "/portfolio", "/alerts",
  "/news", "/macro", "/global", "/quant", "/sharks", "/workspace", "/login",
];

/** /sitemap.xml, generated by the App Router.
 *
 *  lastModified is omitted deliberately: with no build-time date source that is
 *  honest (Date.now() at request time would claim every page changed on every
 *  crawl), a bare <loc> is more truthful than a fabricated <lastmod>. */
export default function sitemap(): MetadataRoute.Sitemap {
  return ROUTES.map((path) => ({
    url: `${SITE}${path}`,
    changeFrequency: path === "" ? "daily" : "weekly",
    priority: path === "" ? 1 : 0.6,
  }));
}
