import type { MetadataRoute } from "next";

const SITE = "https://financial-terminal-peach.vercel.app";

/** The page a search result should land on. */
const LANDING = "/product";

// Only pages a crawler can actually READ without signing in.
//
// This used to list every app route, and that was worse than listing none.
// Every page in this app is "use client" behind an auth gate, so the
// prerendered HTML a crawler receives is the app CHROME — nav labels and a
// tooltip. Measured: "/" served 1396 characters of indexable text, none of it
// describing the product, and /terminal served 31. So the sitemap was
// recommending that Google index a dashboard shell as the product's front
// door, and the page description it would have chosen was tooltip prose about
// data connections.
//
// src/lib/__tests__/sitemap.test.ts enforces the rule: nothing that imports
// Shell belongs here.
//
// Worth revisiting if the ticker pages ever get server-rendered content —
// /terminal?t=RELIANCE.NS would be a genuinely valuable SEO surface if it
// rendered the company's figures. Today it renders 31 characters.
const ROUTES = [
  // The landing page first: it is the only route that exists to be found.
  "/product", "/login", "/privacy", "/terms", "/disclosures",
];

/** /sitemap.xml, generated by the App Router.
 *
 *  lastModified is omitted deliberately: with no build-time date source that is
 *  honest (Date.now() at request time would claim every page changed on every
 *  crawl), a bare <loc> is more truthful than a fabricated <lastmod>. */
export default function sitemap(): MetadataRoute.Sitemap {
  // Compared against the landing route, not against "". Every entry in
  // ROUTES carries a leading slash, so the old `path === ""` test could never
  // match — the built sitemap gave every URL weekly/0.6 and had no priority-1
  // entry at all. A dead branch that looks like it is doing something.
  return ROUTES.map((path) => ({
    url: `${SITE}${path}`,
    changeFrequency: path === LANDING ? "weekly" : "monthly",
    priority: path === LANDING ? 1 : 0.5,
  }));
}
