"use client";

/**
 * Uniform data-provenance badges: every page labels its data the same way
 * instead of ad-hoc prose. Part of the app's "honesty" pattern.
 *
 *  LIVE          polling right now (row auto-refreshes while visible)
 *  DELAYED       server-cached snapshot, refreshed on a TTL
 *  EOD           end-of-day publication (e.g. NSE bulk/block deals)
 *  AI-ESTIMATED  model-generated content — verify before relying on it
 *  STALE         provider is failing; showing last-known-good cached data
 */
export type DataStatus = "live" | "delayed" | "eod" | "ai" | "stale";

const STYLES: Record<DataStatus, { label: string; cls: string; title: string }> = {
  live: {
    label: "LIVE", cls: "border-green/60 text-green",
    title: "Auto-refreshing while this tab is visible.",
  },
  delayed: {
    label: "DELAYED", cls: "border-amber/60 text-amber",
    title: "Server-cached snapshot refreshed periodically — not tick-by-tick.",
  },
  eod: {
    label: "EOD", cls: "border-line2 text-mut",
    title: "Published end-of-day by the source; intraday updates don't exist.",
  },
  ai: {
    label: "AI-ESTIMATED", cls: "border-purple-400/60 text-purple-300",
    title: "Generated by an AI model from public data — educational, not verified, not advice.",
  },
  stale: {
    label: "STALE", cls: "border-red/60 text-red",
    title: "The data provider is currently failing — showing the last good copy.",
  },
};

export function StatusBadge({ kind, asOf, className }: {
  kind: DataStatus;
  /** Optional timestamp (ISO or preformatted) appended as "· as of X". */
  asOf?: string | null;
  className?: string;
}) {
  const s = STYLES[kind];
  const when = asOf ? ` · as of ${asOf.replace("T", " ").slice(0, 16)}` : "";
  return (
    <span
      title={s.title}
      className={`inline-flex items-center px-1.5 py-0.5 rounded border text-[9px] uppercase tracking-wider cursor-help ${s.cls} ${className ?? ""}`}
    >
      {s.label}{when}
    </span>
  );
}
